language: java
jdk:
  - openjdk17

branches:
  only:
    - master # travis CI를 어느 브랜치가 푸시될 때 수행할지 지정

# Travis CI 서버의 Home
cache: #그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때 받지 않도록
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build" #master 브랜치에 푸시되었을 때, 수행하는 명령어

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성(travisCI는 S3에 디렉토리 단위로만 업로드할 수 있기 때문에 꼭 필요한 절차)
  - cp scripts/*.sh before-deploy/ # before-deploy에는 zip 파일에 포함시킬 파일을 저장
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy에 들어가서 안의 파일들을 zip으로 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/bohyun-springboot-webservice.zip #deploy로 zip파일 이동
#  - zip -r bohyun-springboot-webservice *
#  - mkdir -p deploy
#  - mv bohyun-springboot-webservice.zip deploy/bohyun-springboot-webservice.zip
# zip파일에 모든 파일들이 들어있을 필요가 없음, Jar, appspec.yml, 배포를 위한 스크립트들만 있으면 됨, 나머지는 필요 x

deploy: #외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된 값
    bucket: bohyun-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리, 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된 값
    bucket: bohyun-springboot-build #S3 버킷
    key: bohyun-springboot-webservice.zip #빌드 파일을 압축해서 전달
    bundle_type: zip #압축 확장자
    application: bohyun-springboot-webservice #웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: bohyun-springboot-webservice-group #웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    region: ap-northeast-2
    wait-until-deployed: true
#git push를 하면 Travis CI를 통해 자동으로 파일이 올려지는 것을 확인할 수 있음

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - qhgus2741@gmail.com