spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        show_sql: true
  profiles:
    include: oauth #스프링에서는 application-xxx.yml(or propertiest)을 이용하면, xxx라는 profile이 해당 yml의 설정을 가져온다
server:
  servlet:
    encoding:
      force-response: true