server:
  port: 8081
  servlet:
    encoding:
      force-response: true
spring:
  profiles:
    include: oauth, real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    store-type: jdbc